---
__php_packages:
  - libpcre3-dev
  - libapache2-mod-php7.1
  - php7.1
  - php7.1-bz2
  - php7.1-cli
  - php7.1-common
  - php7.1-curl
  - php7.1-dev
  - php7.1-fpm
  - php7.1-gd
  - php7.1-imap
  - php7.1-intl
  - php7.1-json
  - php7.1-mbstring
  - php7.1-mcrypt
  - php7.1-opcache
  - php7.1-sqlite3
  - php7.1-xml
  - php7.1-zip
  - php-apcu
  - php-imagick
  - php-xdebug
__php_webserver_daemon: "apache2"

# Vendor-specific configuration paths on Debian/Ubuntu make my brain asplode.
__php_conf_paths:
  - /etc/php/7.1/fpm
  - /etc/php/7.1/apache2
  - /etc/php/7.1/cli

__php_extension_conf_paths:
  - /etc/php/7.1/fpm/conf.d
  - /etc/php/7.1/apache2/conf.d
  - /etc/php/7.1/cli/conf.d

__php_apc_conf_filename: 20-apcu.ini
__php_opcache_conf_filename: 05-opcache.ini
__php_fpm_daemon: php7.1-fpm
__php_fpm_conf_path: "/etc/php/7.1/fpm"
__php_fpm_pool_conf_path: "{{ __php_fpm_conf_path }}/pool.d/www.conf"

__php_fpm_pool_user: www-data
__php_fpm_pool_group: www-data
